### PR TITLE
(#176): Fix horrible code style

### LINKED ISSUE #176: Fix all codestyle
Fix all codestyle according to clang-format

### PR DESCRIPTION
**Pull request by SunnyBerlin**

### CODE REVIEW

File: src/commands/canvas_commands.hpp [hunk 1]
```diff
@@ -6,60 +6,59 @@
...
-            return "dicmdCanvasOrigin"+panDirection2str(T);
-        }
-
-        virtual void execute() {
-             command_manager::getInstance().get_main_renderer()->pan(T);
-             command_manager::getInstance().get_main_widget()->update();
-        }
-
+  public:
+    virtual std::string get_name()
```
Comment (nagaina) [inline src/commands/canvas_commands.hpp:19]: `Please remove the virtual keyboard and you override.

File: src/commands/command_manager.cpp [hunk 2]
```diff
@@ -63,122 +63,128 @@ void command_manager::init() {
...
 
-
-void command_manager::set_main_renderer(renderer* r) 
+void command_manager::set_main_renderer(renderer *r)
 {
     m_renderer = r;
 }
 
-renderer* command_manager::get_main_renderer()
+renderer *command_manager::get_main_renderer()
```
Comment (nagaina) [inline src/commands/command_manager.cpp:175]: This should be considered to be changed into smart ptr

**Review by nagaina — APPROVED** [review]
